spring:
  application:
    name: auth-service

  # ORM
  jpa:
    hibernate:
      ddl-auth: validate
    open-in-view: false

  # POSTGRES DB
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

# SWAGGER
springdoc:
  swagger-ui:
    default-models-expand-depth: -1

jwt:
  secret:
