name: hireboost

services:
  core-service:
    build:
      context: ../              # root context so Dockerfile can see parent pom
      dockerfile: core-service/Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env     # each service should use a unique host port
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

