spring:
  application:
    name: ai-service

server:
  port: 8083

# ORM
  jpa:
    hibernate:
      ddl-auth: validate
    open-in-view: false

# POSTGRES DB
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

# SWAGGER
springdoc:
  swagger-ui:
    default-models-expand-depth: -1