name: hireboost

services:
  auth-service:
    container_name: auth-service
    build:
      context: ../              # root context so Dockerfile can see parent pom
      dockerfile: auth-service/Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - .env     # each service should use a unique host port

